/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/cart`; params?: Router.UnknownInputParams; } | { pathname: `/checkout`; params?: Router.UnknownInputParams; } | { pathname: `/error-boundary`; params?: Router.UnknownInputParams; } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/orders` | `/orders`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/search` | `/search`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile/reviews` | `/profile/reviews`; params?: Router.UnknownInputParams; } | { pathname: `/reviews/write`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } } | { pathname: `/dish/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/kitchen/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/order/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/reviews/dish/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/reviews/edit/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/reviews/kitchen/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/cart`; params?: Router.UnknownOutputParams; } | { pathname: `/checkout`; params?: Router.UnknownOutputParams; } | { pathname: `/error-boundary`; params?: Router.UnknownOutputParams; } | { pathname: `/modal`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/orders` | `/orders`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/search` | `/search`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profile/reviews` | `/profile/reviews`; params?: Router.UnknownOutputParams; } | { pathname: `/reviews/write`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } } | { pathname: `/dish/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/kitchen/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/order/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/reviews/dish/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/reviews/edit/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/reviews/kitchen/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/cart${`?${string}` | `#${string}` | ''}` | `/checkout${`?${string}` | `#${string}` | ''}` | `/error-boundary${`?${string}` | `#${string}` | ''}` | `/modal${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/orders${`?${string}` | `#${string}` | ''}` | `/orders${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/search${`?${string}` | `#${string}` | ''}` | `/search${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profile/reviews${`?${string}` | `#${string}` | ''}` | `/profile/reviews${`?${string}` | `#${string}` | ''}` | `/reviews/write${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/cart`; params?: Router.UnknownInputParams; } | { pathname: `/checkout`; params?: Router.UnknownInputParams; } | { pathname: `/error-boundary`; params?: Router.UnknownInputParams; } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/orders` | `/orders`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/search` | `/search`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile/reviews` | `/profile/reviews`; params?: Router.UnknownInputParams; } | { pathname: `/reviews/write`; params?: Router.UnknownInputParams; } | `/+not-found` | `/dish/${Router.SingleRoutePart<T>}` | `/kitchen/${Router.SingleRoutePart<T>}` | `/order/${Router.SingleRoutePart<T>}` | `/reviews/dish/${Router.SingleRoutePart<T>}` | `/reviews/edit/${Router.SingleRoutePart<T>}` | `/reviews/kitchen/${Router.SingleRoutePart<T>}` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } } | { pathname: `/dish/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/kitchen/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/order/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/reviews/dish/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/reviews/edit/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/reviews/kitchen/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
